name: cmake

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        build_type:
          - Debug
          - Release
        cc:
          - gcc
          - clang

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install libcunit1-dev

    - name: CMake
      run: CC=${{ matrix.cc }} cmake . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      run: cd build && ctest -C ${{ matrix.build_type }} --output-on-failure

  alpine:
    runs-on: ubuntu-22.04
    container:
      image: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine:edge
          - alpine:latest
        build_type:
          - Debug
          - Release
        cc:
          - gcc
          - clang

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: apk --no-cache add build-base cmake cunit-dev ${{ matrix.cc }}

    - name: CMake
      run: CC=${{ matrix.cc }} cmake . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      run: cd build && ctest -C ${{ matrix.build_type }} --output-on-failure

  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
        build_type:
          - Debug
          - Release
        cc:
          - clang

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: brew install cunit

    - name: CMake
      run: CC=${{ matrix.cc }} cmake . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      run: cd build && ctest -C ${{ matrix.build_type }} --output-on-failure

  valgrind:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install libcunit1-dev valgrind

    - name: CMake
      run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=FullDebug -DBUILD_TESTS=ON -DENABLE_VALGRIND=ON

    - name: Build
      run: cmake --build build --config FullDebug

    - name: Test
      run: cd build && ctest -C FullDebug --output-on-failure

  analyzer:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install libcunit1-dev

    - name: CMake
      run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=FullDebug -DBUILD_TESTS=ON -DENABLE_ANALYZER=ON

    - name: Build
      run: cmake --build build --config FullDebug

    - name: Test
      run: cd build && ctest -C FullDebug --output-on-failure

  coverage:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install libcunit1-dev

    - name: CodeCov
      run: |
        cmake . -Bbuild -DCMAKE_BUILD_TYPE=FullDebug -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
        cmake --build build --config FullDebug
        cd build && ctest -C FullDebug --output-on-failure
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
